name: build-onecloud
run-name: build-onecloud github actions
on: 
  workflow_dispatch

jobs:
  gorun:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild Armbian
        uses: armbian/build@v24.2.1
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "onecloud"                   # build target
            
